# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BUHxz_pLRQbybky3o0sS-OQWni_-B_A2
"""
#Bạn A
import math 
from abc import ABC, abstractmethod
from datetime import datetime
from typing import List


class FinancialGoal(ABC):
    """
    Abstract Base Class for all financial goals.
    This class defines the shared structure and behaviors
    of every financial goal in the Smart Savings Navigator system.
    """

    def __init__(
        self,
        goal_id: str,
        goal_name: str,
        target: float,
        start_date: str,
        deadline: str,
        annual_interest_rate: float = 0.0,
        monthly_contribution: float = 0.0,
        goal_type: str = "Generic",
        currency = "VND"
    ):
        self._goal_id = goal_id
        self._goal_name = goal_name
        self._target = target
        self._currency = currency 
        self._balance = 0.0
        self._start_date = datetime.strptime(start_date, "%Y-%m-%d")
        self._deadline = datetime.strptime(deadline, "%Y-%m-%d")
        self._annual_interest_rate = annual_interest_rate
        self._monthly_contribution = monthly_contribution
        self._goal_type = goal_type
        self._status = "In Progress"

    # =========================
    # Getter Methods
    # =========================

    def get_goal_id(self) -> str:
        return self._goal_id

    def get_goal_name(self) -> str:
        return self._goal_name

    def get_target(self) -> float:
        return self._target

    def get_balance(self) -> float:
        return self._balance

    def get_status(self) -> str:
        return self._status

    # =========================
    # Core Financial Actions
    # =========================

    def deposit(self, amount: float):
        if amount <= 0:
            raise ValueError("Deposit amount must be positive.")
        self._balance += amount
        self._update_status()

    def withdraw(self, amount: float):
        if amount <= 0:
            raise ValueError("Withdraw amount must be positive.")
        if amount > self._balance:
            raise ValueError("Insufficient balance.")
        self._balance -= amount
        self._update_status()

    # =========================
    # Progress & Calculation
    # =========================

    def get_progress_percentage(self) -> float:
        if self._target == 0:
            return 0
        return (self._balance / self._target) * 100

    def get_remaining_amount(self) -> float:
        return max(self._target - self._balance, 0)

    def get_remaining_days(self) -> int:
        today = datetime.today()
        return (self._deadline - today).days
    def get_remaining_months(self) -> float:
        return math.ceil(self.get_remaining_days() / 30)

    def _update_status(self):
        if self._balance >= self._target:
            self._status = "Completed"
        else:
            self._status = "In Progress"

    # =========================
    # Abstract Method
    # =========================

    @abstractmethod
    def recalculate_route(self):
        """
        This method must be implemented by subclasses.
        It recalculates the saving plan when user deviates
        from the original contribution plan.
        """
        pass

    # =========================
    # Utility
    # =========================

    def to_dict(self) -> dict:
        return {
            "goal_id": self._goal_id,
            "goal_name": self._goal_name,
            "target": self._target,
            "currency": self._currency,
            "balance": self._balance,
            "start_date": self._start_date.strftime("%Y-%m-%d"),
            "deadline": self._deadline.strftime("%Y-%m-%d"),
            "annual_interest_rate": self._annual_interest_rate,
            "monthly_contribution": self._monthly_contribution,
            "goal_type": self._goal_type,
            "status": self._status
        }


class GoalManager:
    """
    Manages multiple FinancialGoal objects.
    """

    def __init__(self):
        self._goals: List[FinancialGoal] = []

    def add_goal(self, goal: FinancialGoal):
        self._goals.append(goal)

    def remove_goal(self, goal_id: str):
        self._goals = [
            goal for goal in self._goals
            if goal.get_goal_id() != goal_id
        ]

    def find_goal_by_id(self, goal_id: str) -> FinancialGoal:
        for goal in self._goals:
            if goal.get_goal_id() == goal_id:
                return goal
        raise ValueError("Goal not found.")

    def list_goals(self) -> List[FinancialGoal]:
        return self._goals

    def deposit_to_goal(self, goal_id: str, amount: float):
        goal = self.find_goal_by_id(goal_id)
        goal.deposit(amount)

    def withdraw_from_goal(self, goal_id: str, amount: float):
        goal = self.find_goal_by_id(goal_id)
        goal.withdraw(amount)

    def to_list(self) -> List[dict]:
        return [goal.to_dict() for goal in self._goals]

#Bạn C



import sqlite3
from datetime import datetime

class DatabaseManager:
    def __init__(self, db_name="smart_savings.db"):
        self.db_name = db_name
        self._create_tables()

    def _get_connection(self):
        return sqlite3.connect(self.db_name)
    def delete_goal(self, goal_id: str):
        """Xoá mục tiêu và toàn bộ lịch sử giao dịch liên quan."""
        with self._get_connection() as conn:
            # Xoá lịch sử giao dịch trước để tránh lỗi ràng buộc dữ liệu
            conn.execute("DELETE FROM TransactionHistory WHERE goal_id = ?", (goal_id,))
            # Sau đó xoá mục tiêu
            conn.execute("DELETE FROM Goals WHERE goal_id = ?", (goal_id,))
            conn.commit()

    def _create_tables(self):
        query_goals = """
        CREATE TABLE IF NOT EXISTS Goals (
            goal_id TEXT PRIMARY KEY,
            goal_name TEXT NOT NULL,
            target REAL NOT NULL,
            currency TEXT DEFAULT 'VND',
            balance REAL DEFAULT 0.0,
            start_date TEXT NOT NULL,
            deadline TEXT NOT NULL,
            annual_interest_rate REAL DEFAULT 0.0,
            monthly_contribution REAL DEFAULT 0.0,
            goal_type TEXT DEFAULT 'Generic',
            status TEXT DEFAULT 'In Progress'
        );
        """

        query_history = """
        CREATE TABLE IF NOT EXISTS TransactionHistory (
            transaction_id INTEGER PRIMARY KEY AUTOINCREMENT,
            goal_id TEXT NOT NULL,
            amount REAL NOT NULL,
            transaction_type TEXT CHECK(transaction_type IN ('DEPOSIT', 'WITHDRAW')),
            timestamp TEXT NOT NULL,
            FOREIGN KEY (goal_id) REFERENCES Goals (goal_id)
        );
        """

        # Trigger tự động cập nhật số dư khi có giao dịch (Encapsulation ở mức DB)
        trigger_update_balance = """
        CREATE TRIGGER IF NOT EXISTS update_goal_balance
        AFTER INSERT ON TransactionHistory
        BEGIN
            UPDATE Goals
            SET balance = balance + NEW.amount,
                status = CASE
                    WHEN (balance + NEW.amount) >= target THEN 'Completed'
                    ELSE 'In Progress'
                END
            WHERE goal_id = NEW.goal_id;
        END;
        """

        with self._get_connection() as conn:
            cursor = conn.cursor()
            cursor.execute(query_goals)
            cursor.execute(query_history)
            cursor.execute(trigger_update_balance)
            conn.commit()

    # =========================
    # Methods cho Goals
    # =========================

    def save_goal(self, goal_dict: dict):
        """Lưu một đối tượng FinancialGoal (dạng dict) vào DB."""
        query = """
        INSERT OR REPLACE INTO Goals
        (goal_id, goal_name, target, currency, balance, start_date, deadline, annual_interest_rate, monthly_contribution, goal_type, status)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """
        data = (
            goal_dict['goal_id'], goal_dict['goal_name'], goal_dict['target'],
            goal_dict['currency'],
            goal_dict['balance'], goal_dict['start_date'], goal_dict['deadline'],
            goal_dict['annual_interest_rate'], goal_dict['monthly_contribution'],
            goal_dict['goal_type'], goal_dict['status']
        )
        with self._get_connection() as conn:
            conn.execute(query, data)
            conn.commit()

    # =========================
    # Methods cho Transactions
    # =========================

    def add_transaction(self, goal_id: str, amount: float, t_type: str):
        """
        Thực hiện nạp/rút tiền.
        Lưu ý: Không update trực tiếp bảng Goals, Trigger sẽ lo việc đó.
        """
        if t_type == 'WITHDRAW':
            # Kiểm tra số dư trước khi rút (Logic nghiệp vụ)
            current_balance = self.get_goal_balance(goal_id)
            if amount > current_balance:
                raise ValueError("Insufficient balance in database.")
            actual_amount = -amount
        else:
            actual_amount = amount

        query = """
        INSERT INTO TransactionHistory (goal_id, amount, transaction_type, timestamp)
        VALUES (?, ?, ?, ?)
        """
        with self._get_connection() as conn:
            conn.execute(query, (goal_id, actual_amount, t_type, datetime.now().isoformat()))

    def get_goal_balance(self, goal_id: str) -> float:
        query = "SELECT balance FROM Goals WHERE goal_id = ?"
        with self._get_connection() as conn:
            res = conn.execute(query, (goal_id,)).fetchone()
            return res[0] if res else 0.0

    def get_history(self, goal_id: str):
        query = "SELECT * FROM TransactionHistory WHERE goal_id = ? ORDER BY timestamp DESC"
        with self._get_connection() as conn:
            return conn.execute(query, (goal_id,)).fetchall()

if __name__ == "__main__":
    db = DatabaseManager()
    print("")

#Bạn B
from math import log, ceil


class CashGoal(FinancialGoal):
    """
    Savings goal with no interest.
    Suitable for short-term goals such as travel or emergency cash.
    """

    def __init__(
        self,
        goal_id: str,
        goal_name: str,
        target: float,
        start_date: str,
        deadline: str,
        monthly_contribution: float = 0.0,
        currency="VND"
    ):
        super().__init__(
            goal_id=goal_id,
            goal_name=goal_name,
            target=target,
            start_date=start_date,
            deadline=deadline,
            annual_interest_rate=0.0,
            monthly_contribution=monthly_contribution,
            goal_type="CashGoal",
            currency=currency 
        )

    def calculate_required_monthly_saving(self) -> float:
        """
        Calculate the monthly saving needed from now until deadline.
        No interest is applied.
        """
        remaining_amount = self.get_remaining_amount()
        remaining_months = self.get_remaining_months()

        if remaining_amount <= 0:
            return 0.0
        if remaining_months <= 0:
            raise ValueError("Deadline has passed or no time remaining.")

        return remaining_amount / remaining_months

    def recalculate_route(self) -> dict:
        """
        Recalculate the route when actual saving differs from the original plan.
        """
        remaining_amount = self.get_remaining_amount()
        remaining_months = self.get_remaining_months()

        if remaining_amount <= 0:
            new_monthly = 0.0
            catch_up_per_month = 0.0
            status_message = "Goal already completed."
        elif remaining_months <= 0:
            raise ValueError("Cannot recalculate route because the deadline has passed.")
        else:
            new_monthly = remaining_amount / remaining_months
            catch_up_per_month = max(new_monthly - self._monthly_contribution, 0.0)
            status_message = "Route recalculated successfully."

        return {
            "goal_id": self._goal_id,
            "goal_name": self._goal_name,
            "goal_type": self._goal_type,
            "current_balance": self._balance,
            "target": self._target,
            "remaining_amount": remaining_amount,
            "remaining_months": remaining_months,
            "new_monthly_required": new_monthly,
            "catch_up_per_month": catch_up_per_month,
            "projected_final_amount": self._balance + new_monthly * max(remaining_months, 0),
            "status_message": status_message
        }


class BankGoal(FinancialGoal):
    """
    Savings goal with compound interest.
    Suitable for medium/long-term goals such as car or house purchase.
    Includes roll-over logic when the remaining term is below 30 days.
    """

    def __init__(
        self,
        goal_id: str,
        goal_name: str,
        target: float,
        start_date: str,
        deadline: str,
        annual_interest_rate: float,
        monthly_contribution: float = 0.0,
        compounding_per_year: int = 12,
        term_days: int = 30,
        currency="VND"
    ):
        super().__init__(
            goal_id=goal_id,
            goal_name=goal_name,
            target=target,
            start_date=start_date,
            deadline=deadline,
            annual_interest_rate=annual_interest_rate,
            monthly_contribution=monthly_contribution,
            goal_type="BankGoal",
            currency=currency
        )

        if annual_interest_rate < 0:
            raise ValueError("Annual interest rate cannot be negative.")
        if compounding_per_year <= 0:
            raise ValueError("Compounding frequency must be positive.")
        if term_days <= 0:
            raise ValueError("Term days must be positive.")

        self._compounding_per_year = compounding_per_year
        self._term_days = term_days

    # =========================
    # Interest / Projection Helpers
    # =========================

    def get_periodic_rate(self) -> float:
        """
        Convert annual interest rate to periodic rate.
        Example: annual 6% with monthly compounding => 0.06 / 12
        """
        return self._annual_interest_rate / self._compounding_per_year

    def calculate_compound_amount(self, principal: float, periods: float) -> float:
        """
        Compound interest formula:
        A = P(1 + r/n)^(nt)

        Here periods is the number of compounding periods remaining.
        """
        if principal < 0:
            raise ValueError("Principal cannot be negative.")
        if periods < 0:
            raise ValueError("Periods cannot be negative.")

        periodic_rate = self.get_periodic_rate()
        return principal * ((1 + periodic_rate) ** periods)

    def project_current_balance_to_deadline(self) -> float:
        """
        Project the current balance to the deadline with compound interest only,
        without adding future monthly contributions.
        """
        remaining_months = self.get_remaining_months()
        if remaining_months <= 0:
            return self._balance

        return self.calculate_compound_amount(self._balance, remaining_months)

    def apply_rollover_if_needed(self) -> float:
        """
        Simulate roll-over logic:
        If less than 30 days remain until maturity/deadline,
        the current balance is assumed to be rolled over once more
        for the remaining fraction of the month.

        This returns a projected balance, not a direct mutation.
        """
        remaining_days = self.get_remaining_days()

        if remaining_days <= 0:
            return self._balance

        periodic_rate = self.get_periodic_rate()

        # Normal monthly compounding for full months
        full_months = int(remaining_days // 30)
        projected_balance = self._balance * ((1 + periodic_rate) ** full_months)

        # Remaining days less than 30 -> simulate short rollover / proportional accrual
        extra_days = remaining_days % 30
        if 0 < extra_days < 30:
            projected_balance *= (1 + periodic_rate * (extra_days / 30))

        return projected_balance

    def project_final_amount_with_monthly_contributions(self, monthly_saving: float) -> float:
        """
        Project future value with:
        - existing balance compounded forward
        - monthly contributions added at the end of each month
        - roll-over logic for the final incomplete period (< 30 days)

        Assumption:
        monthly_saving is deposited once per month.
        """
        remaining_days = self.get_remaining_days()

        if remaining_days <= 0:
            return self._balance

        periodic_rate = self.get_periodic_rate()
        full_months = int(remaining_days // 30)
        extra_days = remaining_days % 30

        # Future value of current balance over full months
        future_value = self._balance * ((1 + periodic_rate) ** full_months)

        # Future value of monthly contributions over full months
        if full_months > 0 and monthly_saving > 0:
            for month_index in range(full_months):
                periods_left = full_months - month_index - 1
                future_value += monthly_saving * ((1 + periodic_rate) ** periods_left)

        # Final partial-period rollover (< 30 days)
        if 0 < extra_days < 30:
            future_value *= (1 + periodic_rate * (extra_days / 30))

        return future_value

    def calculate_required_monthly_saving(self) -> float:
        """
        Estimate the monthly saving needed to reach target before deadline,
        considering compound interest.

        Uses iterative search for robustness and readability.
        """
        remaining_months = self.get_remaining_months()
        remaining_days = self.get_remaining_days()

        if self.get_remaining_amount() <= 0:
            return 0.0
        if remaining_days <= 0:
            raise ValueError("Deadline has passed or no time remaining.")

        low = 0.0
        high = self._target
        tolerance = 0.01

        for _ in range(100):
            mid = (low + high) / 2
            projected = self.project_final_amount_with_monthly_contributions(mid)

            if abs(projected - self._target) <= tolerance:
                return mid

            if projected < self._target:
                low = mid
            else:
                high = mid

        return (low + high) / 2
    
    # Thêm sensitivity
    def calculate_required_monthly_saving_for_rate(self, annual_rate: float) -> float:
        if annual_rate < 0:
            raise ValueError("Annual interest rate cannot be negative.")

        remaining_days = self.get_remaining_days()
        if self.get_remaining_amount() <= 0:
            return 0.0
        if remaining_days <= 0:
            raise ValueError("Deadline has passed or no time remaining.")

        original_rate = self._annual_interest_rate
        self._annual_interest_rate = annual_rate

        try:
            low = 0.0
            high = self._target
            tolerance = 0.01

            for _ in range(100):
                mid = (low + high) / 2
                projected = self.project_final_amount_with_monthly_contributions(mid)

                if abs(projected - self._target) <= tolerance:
                    return mid

                if projected < self._target:
                    low = mid
                else:
                    high = mid

            return (low + high) / 2

        finally:
            self._annual_interest_rate = original_rate


    def analyze_interest_sensitivity(self, rate_scenarios) -> list:
        results = []

        current_required = self.calculate_required_monthly_saving()

        if isinstance(rate_scenarios, dict):
            iterable_data = [{"bank": bank_name, "rate": rate} for bank_name, rate in rate_scenarios.items()]
        else:
            iterable_data = rate_scenarios

        for item in iterable_data:
            bank_name = item["bank"]
            rate = float(item["rate"])

            required_monthly = self.calculate_required_monthly_saving_for_rate(rate)
            monthly_difference = current_required - required_monthly

            results.append({
                "goal_id": self._goal_id,
                "goal_name": self._goal_name,
                "bank": bank_name,
                "annual_interest_rate": rate,
                "required_monthly_saving": required_monthly,
                "monthly_saving_difference": monthly_difference,
                "better_than_current": monthly_difference > 0
            })

        results.sort(key=lambda x: x["required_monthly_saving"])
        return results

    def estimate_months_to_target(self, monthly_saving: float) -> int:
        """
        Estimate how many months are needed to reach the target
        with a given monthly saving amount.
        """
        if monthly_saving < 0:
            raise ValueError("Monthly saving cannot be negative.")

        periodic_rate = self.get_periodic_rate()
        balance = self._balance
        months = 0

        if balance >= self._target:
            return 0

        while balance < self._target and months < 1200:
            balance = balance * (1 + periodic_rate) + monthly_saving
            months += 1

        if months >= 1200:
            raise ValueError("Target is too far or monthly saving is too low to estimate.")

        return months

    # =========================
    # Required Abstract Method
    # =========================

    def recalculate_route(self) -> dict:
        """
        Recalculate route for bank savings.
        Logic:
        1. Project the existing balance with simulated bank interest.
        2. Use that projected interest effect to reduce the remaining burden.
        3. Recompute the new monthly saving needed.
        """
        remaining_days = self.get_remaining_days()
        remaining_months = self.get_remaining_months()

        if self._balance >= self._target:
            return {
                "goal_id": self._goal_id,
                "goal_name": self._goal_name,
                "goal_type": self._goal_type,
                "current_balance": self._balance,
                "target": self._target,
                "remaining_amount": 0.0,
                "remaining_months": max(remaining_months, 0),
                "projected_balance_with_interest": self._balance,
                "interest_gain_projection": 0.0,
                "new_monthly_required": 0.0,
                "catch_up_per_month": 0.0,
                "status_message": "Goal already completed."
            }

        if remaining_days <= 0:
            raise ValueError("Cannot recalculate route because the deadline has passed.")

        projected_balance = self.apply_rollover_if_needed()
        interest_gain_projection = max(projected_balance - self._balance, 0.0)

        new_monthly_required = self.calculate_required_monthly_saving()
        catch_up_per_month = max(new_monthly_required - self._monthly_contribution, 0.0)

        projected_final_amount = self.project_final_amount_with_monthly_contributions(
            new_monthly_required
        )

        return {
            "goal_id": self._goal_id,
            "goal_name": self._goal_name,
            "goal_type": self._goal_type,
            "current_balance": self._balance,
            "target": self._target,
            "remaining_amount": self.get_remaining_amount(),
            "remaining_months": remaining_months,
            "projected_balance_with_interest": projected_balance,
            "interest_gain_projection": interest_gain_projection,
            "new_monthly_required": new_monthly_required,
            "catch_up_per_month": catch_up_per_month,
            "projected_final_amount": projected_final_amount,
            "status_message": "Route recalculated successfully."
        }

    # =========================
    # Optional Utility
    # =========================

    def to_dict(self) -> dict:
        data = super().to_dict()
        data["compounding_per_year"] = self._compounding_per_year
        data["term_days"] = self._term_days
        return data
